[uwsgi]
# Toolforge Kubernetes webservice — Python 3.13
module        = wsgi:application
master        = true
processes     = 1
threads       = 16
vacuum        = true
logto         = /dev/stdout
log-date      = true
lazy-apps     = false
die-on-term   = true
buffer-size   = 65535
harakiri      = 120
harakiri-verbose = true
